### ISSUE TITLE
Change CESM's default aoflux_grid to xgrid

### ISSUE THREAD

**Issue by billsacks** [ESCOMP/CMEPS#502]
We want to use the exchange grid by default for the aoflux_grid.

There have been some issues getting this to work in all cases, but we seem to be getting closer to having this working. Specifically:
- [ ] @oehmke has a fix for an issue with 2nd-order-conservative mapping with the exchange grid that can show up with certain grids (though not in CESM's current prealpha test suite). This should make it into the ESMF 8.8 development code base soon.
- [x] #501 fixes some CMEPS issues with add_gusts false
- [x] (Edit: Added 2024-09-30) #506 fixes xgrid reproducibility
- [x] (Edit: Added 2024-10-01) Resolve #510 
- [x] (Edit: Added 2024-10-18) Merge #514 

After those three pieces are ready and we have updated CESM to point to an ESMF development snapshot with the fix noted above, I think we should switch the default to aoflux_grid to "xgrid" so that we are testing with that configuration. @jedwards4b do you agree with this timing?

**Comment by jedwards4b** [comment]
Yes, I agree - can we do this as part of the beta04 tag?

**Comment by billsacks** [comment]
> Yes, I agree - can we do this as part of the beta04 tag?

That sounds good as a goal. I'm thinking that we should wait to change the CESM default until we have an updated ESMF tag, which is still going to be a little while before it's ready, so the timing will depend on that. My thinking is that, even though the standard CESM configurations don't seem to need this ESMF fix, there are probably some less-common configurations that will trigger the error you reported last year, so it will be best to have a fix in place in ESMF before we switch over to using xgrid by default... but I don't feel strongly about that plan if you or others would like to move ahead sooner with the switch to xgrid by default.

**Comment by billsacks** [comment]
When we make this change, I feel we should introduce at least one test – probably in aux_cmeps, but maybe in CESM's prealpha / prebeta test suite – that tests with aoflux_grid = ogrid, to make sure that option continues to work.

**Comment by billsacks** [comment]
We should also resolve #510 . (I have added this to the initial comment above.)
